### ISSUE TITLE
Minecaft always on top of other windows.

### ISSUE THREAD

**Issue by ItsPasi** [Kira-NT/cubes-with-borders#1]
The current mod is always on top of other windows so I can't really switch between programs with this easily. Hope there is a simple fix.

**Comment by Kira-NT** [comment]
Oh, you’re already here. So, no element of surprise then, huh?

Yep, this is by design. The fullscreen mode so exclusive, it could have become the head of the RNC.

I didn’t know the limits of what’s acceptable in your holy wars against input lag, and what’s not, so context switching is also disabled. If this is a wanted feature, I’ll make it into a two-lines-of-code mod. Give me a moment.

**Comment by Kira-NT** [comment]
You can get the updated mod before I push the actual release here: https://github.com/Kir-Antipov/cubes-with-borders/actions/runs/9809845369.

Let me know if there's something else you need :)

**Comment by ItsPasi** [comment]
Works perfectly thanks :)

Also I just wanted to say that my assumption was wrong that you can have a v-sync free window. I'm not sure which games utilize it but I realized after trying the Latency Split Test program again, which even in its normal windowed mode has visible screen tearing, which only goes away when I play a video or have some kind of movement on that screen. Maybe you could find out how that works?

You can find the program on the official aperturegrille website but I don't think it's open source.

**Comment by Kira-NT** [comment]
> Works perfectly thanks :)

Okie-dokie, gonna publish a new release then. Just to reiterate, unless Mojang suddenly decides to port Minecraft to Vulkan or something, this mod should work forever. Unfortunately, Modrinth and CurseForge don't allow specifying version ranges in the compatibility matrix, so I still need to manually update the list of supported Minecraft versions on both platforms for your launcher to allow installing the mod on the latest game update. Feel free to ping me whenever it needs to be done if I forget to do it myself (I will) :)

> Also I just wanted to say that my assumption was wrong that you can[not?] have a v-sync free window.

Well, it's not, really. DWM has worked this way since it was introduced with Windows 7+. For it to work differently, you would need to create a primary buffer around the floating window in question, instead of the whole desktop. I don't think Windows does this under any circumstances. At least, there's no documentation on the existence of such a feature. So, as far as I'm concerned, it doesn't exist :D
