### ISSUE TITLE
Minecraft is ALWAYS on top of other windows, even in windowed mode (similar to #1)

### ISSUE THREAD

**Issue by slushieuwu** [Kira-NT/cubes-with-borders#2]
in this image, my browser is the focused application

![image](https://github.com/Kir-Antipov/cubes-with-borders/assets/86991346/6bdc6f80-3e5c-4e31-8d12-82bf1cbd5deb)

**Comment by slushieuwu** [comment]
was this supposed to be fixed after #1 ?

**Comment by Kira-NT** [comment]
This is not this mod's problem. It has nothing to do with windowed mode.

Here's the full code of this disappointment:

https://github.com/Kir-Antipov/cubes-with-borders/blob/6f2f7449a3349274dead712f875c63550b78f826/src/main/java/dev/kir/cubeswithborders/client/mixin/WindowMixin.java#L27-L54

**Comment by slushieuwu** [comment]
hmmm...

_hang on_

after a restart its fixed itself anyways

**Comment by slushieuwu** [comment]
so now i have no idea where its coming from :'p

welp ill hope it doesnt pop up again, sorry for being mistaken :p

**Comment by Kira-NT** [comment]
#1 was a different beast - compositing was disabled while Minecraft was in fullscreen *(it's called exclusive fullscreen for a reason)*. To enable it, you need to untether the window from a monitor with a few additional requirements, which I did. This change, by its nature, only affects the game while it's in fullscreen.

However, I have a feeling that you still have Cubes Without Borders installed, and this problem was triggered by it, because it explicitly changes the Z-order of the window on Windows. So, maybe some changes in that regard that shouldn't have stuck did indeed stick.

**Comment by slushieuwu** [comment]
_oh_ i did forget to disable that one..

does that mean i should make an issue about it there? :p or should i not bother

**Comment by Kira-NT** [comment]
If you don't mind :)

I'll need to look into that when my Windows friend is available. I guess, `HWND_NOTOPMOST` is not reset whenever the game window leaves borderless fullscreen for some ungodly reason.

**Comment by slushieuwu** [comment]
👍
