### ISSUE TITLE
[Incompatibility] Certain parts of the world look weird when the window is unfocused when using BlurredWindow for some reason.

### ISSUE THREAD

**Issue by slushieuwu** [Kira-NT/cubes-with-borders#3]
I assumed the issues would only be on the title screen, yet somehow ingame is also affected (id brought this up previously on their end, decided to bring it here too)

![image](https://github.com/Kir-Antipov/cubes-with-borders/assets/86991346/96c5720d-7c7e-435d-8cbb-1764dd5a6889)

![image](https://github.com/Kir-Antipov/cubes-with-borders/assets/86991346/029fe7fe-c509-401f-9f20-198897fb873d)

**Comment by slushieuwu** [comment]
(also sorry if you already went over this in the other issue i made on CW/oB :p)

**Comment by Kira-NT** [comment]
CW/oB is as simple, primitive even, as it gets. Therefore, I would hesitate to work on fixing actual bugs here *(for example, I know for sure that it creates one very specific bug, but since it's non-obtrusive and can be triggered only in conjunction with other mods, I sacrificed it to the compatibility gods)*, and this particular one is certainly not this mod's problem :D

If I were to assume what's happening here, it's either that the lighting is messed up, or maybe your desktop colors are bleeding through translucent layers. Since `BlurredWindow` does touch some rendering logic here and there, this might be an actual problem with their implementation, which simply doesn't show itself when the window doesn't allow compositing under any circumstances *(i.e., when Minecraft window uses regular, non-modified exclusive fullscreen)*. So, maybe this also causes those flickers when CWB is enabled?
